added new stuff
indieSoftware/INCommons pull request #16
Opened 2024-12-05 13:23 UTC by shotikoKlibadze

2024-12-05 15:56 UTC, SvenKorset commented on Sources/INCommons/Swift/Extensions/Array+OrderedIndex.swift
> +	func orderedIndexOf(_ element: Element, isOrderedBefore: (_ lhs: Element, _ rhs: Element) -> Bool) -> Int {
Where is the unit test for this?

2024-12-05 15:56 UTC, SvenKorset commented on Sources/INCommons/Swift/Types/LoadingHandler.swift
> +/// to prevent race conditions.
This comment needs to be rewritten to reflect a general case and not to be bound to a fictional CalendarManager which doesn't exist in this package.

2024-12-05 15:56 UTC, SvenKorset commented on Sources/INCommons/Swift/Types/LoadingHandler.swift
> +actor LoadingHandler {
Unit test?

2024-12-08 19:31 UTC, SvenKorset requested changes

2024-12-08 19:31 UTC, SvenKorset commented on Tests/INCommonsTests/Swift/Extensions/Collection/Collection+OrderedIndex.swift
> +final class Array: XCTestCase {
Please name the file "Array+OrderedIndexTests.swift" and match the test case to the type with the "Tests" extension.
```suggestion
final class Array_OrderedIndexTests: XCTestCase {
```

2024-12-08 19:31 UTC, SvenKorset commented on Tests/INCommonsTests/Swift/Types/LoadingHandler/LoadingHandlerTests.swift
> +		try? await Task.sleep(nanoseconds: 200_000_000) // Wait briefly to ensure all tasks are complete
This is a bad test design in my opinion because you are doing expectations when a task will be executed again. Such tests lead to flakiness because those assumptions are not always true. When the test machine is very busy or for some other reasons a task might be delayed further and then it suddenly fails your tests. You should never do assumptions like "after some time the task will be executed". Instead you should have hard rules, like Swift's concurrency with async/await is doing. With an await you are for example not doing any assumptions about a timing, but are strictly waiting for the other task being executed regardless of how long it takes. If it's not possible to use async/await then at least use expectations. But try to not use any sleeps with time, this usually makes the test only take longer than necessary. Please have a look at the original test, why not using that?

2024-12-09 11:17 UTC, shotikoKlibadze commented on Tests/INCommonsTests/Swift/Types/LoadingHandler/LoadingHandlerTests.swift
> +		try? await Task.sleep(nanoseconds: 200_000_000) // Wait briefly to ensure all tasks are complete
since i didnt write those test i didn't know they existed :D I will use the original tests

2024-12-09 11:27 UTC, SvenKorset approved these changes

2024-12-16 17:20 UTC, merged