Added concurrency check and fixes
indieSoftware/INCommons pull request #5
Opened 2022-10-01 09:59 UTC by SvenKorset

Enabled the concurrency compiler warning flag and solved some warnings by applying the actor and sendable annotations.

2022-10-06 21:23 UTC, huseyinbagana requested changes

2022-10-06 21:23 UTC, huseyinbagana commented on Sources/INCommons/UIKit/UIDeviceProvider.swift
>  		orientationDidChangeNotificationToken = NotificationCenter.default.addObserver(
Indentations looks a bit much in my screen

2022-10-06 21:23 UTC, huseyinbagana commented on Sources/INCommons/UIKit/UIDeviceProvider.swift
> +			await MainActor.run {
Why dont we use await directly

2022-10-07 13:47 UTC, SvenKorset commented on Sources/INCommons/UIKit/UIDeviceProvider.swift
>  		orientationDidChangeNotificationToken = NotificationCenter.default.addObserver(
It's the common indention auto-formatted by SwiftFormat.

2022-10-09 10:23 UTC, huseyinbagana approved these changes

2022-10-09 13:31 UTC, merged