Scripts updated and project fixed
indieSoftware/INCommons pull request #6
Opened 2022-10-01 14:08 UTC by SvenKorset

Updated the scripts and fixed the project according to the new linter rules

2022-10-06 21:27 UTC, huseyinbagana requested changes

2022-10-06 21:27 UTC, huseyinbagana commented on Sources/INCommons/UIKit/UIDeviceProvider.swift
> +#if targetEnvironment(simulator)
Maybe we can create a property wrapper which is checking targetEnvironment

2022-10-07 13:41 UTC, SvenKorset commented on Sources/INCommons/UIKit/UIDeviceProvider.swift
> +#if targetEnvironment(simulator)
Well, to be honest I don't see the benefit of creating a 10+ loc property wrapper to replace a single line of code. Especially because a property wrapper is meant to be re-used, what we actually wouldn't.

2022-10-09 10:26 UTC, huseyinbagana approved these changes

2022-10-09 13:27 UTC, merged